# -*- coding: utf-8 -*-
"""Agrupacionipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y5mSNlIqRpYuqZxepCalzMHa_qNwoBX4
"""

import pandas as pd
import numpy as np

url="https://raw.githubusercontent.com/JUAN-32/Parcial4_JuanCortez_2500952022/refs/heads/main/raw/clave_I_agrupacion.csv"
df= pd.read_csv(url)
df.head()

print("Primeras filas:")
print(df.head())

print("\nDimensiones:")
print(df.shape)

print("\nInformación general:")
print(df.info())

print("\nValores nulos:")
print(df.isnull().sum())

print("\nDuplicados:")
print(df.duplicated().sum())

print("\nEstadística descriptiva:")
print(df.describe())

# =====================================================
# 4. LIMPIAR NOMBRES DE COLUMNAS
# =====================================================

df.columns = (
    df.columns
    .str.strip()
    .str.replace(" ", "_")
)

print("\nColumnas:")
print(df.columns.tolist())

# =====================================================
# 5. SELECCIONAR VARIABLES PARA CLUSTERING
# =====================================================

variables = df[[
    "ingresos",
    "gasto_promedio"
]]

print("\nVariables seleccionadas:")
print(variables.head())

from sklearn.preprocessing import StandardScaler

# =====================================================
# 6. ESCALAR DATOS
# =====================================================

scaler = StandardScaler()

datos_escalados = scaler.fit_transform(variables)

from sklearn.cluster import KMeans

# =====================================================
# 7. MÉTODO DEL CODO
# =====================================================

inercias = []

for k in range(1, 11):

    modelo = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    modelo.fit(datos_escalados)

    inercias.append(modelo.inertia_)

import matplotlib.pyplot as plt

# 8. GRÁFICO DEL CODO
# =====================================================

plt.figure(figsize=(8,5))

plt.plot(
    range(1,11),
    inercias,
    marker="o"
)

plt.title("Método del Codo")
plt.xlabel("Número de Clusters")
plt.ylabel("Inercia")

plt.show()

# =====================================================
# 9. APLICAR K-MEANS
# =====================================================

kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

clusters = kmeans.fit_predict(datos_escalados)

# =====================================================
# 10. AGREGAR CLUSTER AL DATASET
# =====================================================

df["Cluster"] = clusters

# =====================================================
# 11. MOSTRAR RESULTADOS
# =====================================================

print("\nDataset con clusters:")
print(df.head())

print("\nCantidad de registros por cluster:")
print(df["Cluster"].value_counts())

# =====================================================
# 12. PROMEDIOS POR CLUSTER
# =====================================================

print("\nPromedio por cluster:")
print(df.groupby("Cluster").mean(numeric_only=True))

# =====================================================
# 13. VISUALIZAR CLUSTERS
# =====================================================

plt.figure(figsize=(8,6))

plt.scatter(
    df["ingresos"],
    df["gasto_promedio"],
    c=df["Cluster"]
)

plt.xlabel("Ingresos")
plt.ylabel("Gasto Promedio")

plt.title("Clusters encontrados con K-Means")

plt.show()

"""### Distribución de Edad por Cluster

Este gráfico de violín muestra la distribución de la edad de los clientes en cada cluster. Podemos observar cómo la edad varía significativamente entre los clusters, apoyando la interpretación de que algunos clusters representan grupos de edad específicos.
"""

# =====================================================
# 14. GUARDAR DATASET FINAL
# =====================================================

df.to_csv(
    "dataset_final_clusters.csv",
    index=False
)

print("\nDataset guardado correctamente.")