# -*- coding: utf-8 -*-
"""Correlacionipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E1sFC1aQFfTfj6NvNGl8I_wnlV2d_vYE
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

url="https://raw.githubusercontent.com/JUAN-32/Parcial4_JuanCortez_2500952022/refs/heads/main/raw/clave_I_correlacion.csv"
df= pd.read_csv(url)
df.head()

df.info()

#estadistica discriptiva
df.describe()

#Validar valores nulos
df.isnull().sum()

#Seleccionar datos numéricos
df_numeric = df.select_dtypes(include=['number'])

#Calcular correlación
matriz = df_numeric.corr()
matriz

#Visualización
plt.figure(figsize=(10,6))
sns.heatmap(matriz, annot=True, cmap="coolwarm")
plt.title("Matriz de correlación")
plt.show()